import { defineNuxtConfig } from "nuxt/config";

export default defineNuxtConfig({
  compatibilityDate: "2026-01-30",
  // Global page headers
  app: {
    head: {
      title: "个人博客",
      meta: [
        { charset: "utf-8" },
        { name: "viewport", content: "width=device-width,initial-scale=1" },
        { name: "description", content: "个人博客，使用 Nuxt 3 + Content" },
      ],
    },
  },

  // Modules
  modules: [
    "@nuxt/content",
    "@nuxtjs/tailwindcss",
    "@pinia/nuxt",
    "@vueuse/nuxt",
  ],

  // Content module config
  content: {
    // files are placed under the `content/` directory
    // enable markdown frontmatter schema if needed later
  },

  // TailwindCSS config path (generated by @nuxtjs/tailwindcss)
  css: ["@/assets/css/tailwind.css"],

  // Build settings
  build: {
    transpile: ["motion-v"],
  },

  nitro: {
    preset: "netlify",
  },

  // 强制使用单一 Vue 实例，避免 motion-v 等库在 renderSlot 时 currentRenderingInstance 为 null
  vite: {
    resolve: {
      dedupe: ["vue", "vue-demi"],
    },
  },

  // Runtime config (placeholder for API keys etc.)
  runtimeConfig: {
    giscusToken: "",
    public: {
      giscusRepo: "",
      giscusRepoId: "",
      giscusCategory: "Announcements",
      giscusCategoryId: "",
      giscusTheme: "dark",
      statsBase: "",
    },
  },
});
