import { readdirSync } from "node:fs";
import { join } from "node:path";
import { defineNuxtConfig } from "nuxt/config";

const collectRoutes = (dir: string, base: string): string[] => {
  try {
    const entries = readdirSync(dir, { withFileTypes: true });
    return entries
      .filter((entry) => entry.isFile())
      .map((entry) => entry.name)
      .filter((name) => name.endsWith(".md") || name.endsWith(".json"))
      .map((name) => name.replace(/\.(md|json)$/, ""))
      .map((slug) => `${base}/${slug}`);
  } catch {
    return [];
  }
};

const blogRoutes = collectRoutes(
  join(process.cwd(), "content", "blog"),
  "/blog",
);
const snapshotRoutes = collectRoutes(
  join(process.cwd(), "content", "snapshots"),
  "/snapshots",
);
// 顶层文章路由 /:slug，使 GitHub Pages base /blog/ 下文章 URL 为 /blog/:slug
const articleSlugRoutes = collectRoutes(
  join(process.cwd(), "content", "blog"),
  "",
).map((s) => (s.startsWith("/") ? s : `/${s}`));
const isGhPages = process.env.NUXT_GH_PAGES === "true";
const appBase = process.env.NUXT_APP_BASE_URL || "/";
const cdnBase = process.env.NUXT_APP_CDN_URL || "";
const normalizedBase = appBase.endsWith("/") ? appBase : `${appBase}/`;
const baseRoutes = [
  "/",
  "/blog",
  "/snapshots",
  "/stats",
  ...articleSlugRoutes,
  ...blogRoutes,
  ...snapshotRoutes,
];
const withTrailingSlash = (route: string) =>
  route === "/" ? route : route.endsWith("/") ? route : `${route}/`;
const prerenderRoutes = Array.from(
  new Set([
    ...baseRoutes,
    ...baseRoutes.map(withTrailingSlash),
  ]),
);

export default defineNuxtConfig({
  compatibilityDate: "2026-01-30",
  // Global page headers
  app: {
    head: {
      title: "个人博客",
      meta: [
        { charset: "utf-8" },
        { name: "viewport", content: "width=device-width,initial-scale=1" },
        { name: "description", content: "个人博客，使用 Nuxt 3 + Content" },
      ],
      link: [
        { rel: "preconnect", href: "https://fonts.googleapis.com" },
        { rel: "preconnect", href: "https://fonts.gstatic.com", crossorigin: "" },
        { rel: "dns-prefetch", href: "https://giscus.app" },
        { rel: "dns-prefetch", href: "https://github.githubassets.com" },
        { rel: "dns-prefetch", href: "https://github.com" },
        { rel: "dns-prefetch", href: "https://api.github.com" },
        { rel: "preconnect", href: "https://giscus.app", crossorigin: "" },
        { rel: "preconnect", href: "https://github.githubassets.com", crossorigin: "" },
      ],
    },
    baseURL: appBase,
    cdnURL: cdnBase,
    buildAssetsDir: "/_nuxt/",
  },

  // Modules
  modules: [
    "@nuxt/content",
    "@nuxtjs/tailwindcss",
    "@pinia/nuxt",
    "@vueuse/nuxt",
  ],

  // Content module config
  content: {
    // files are placed under the `content/` directory
    // enable markdown frontmatter schema if needed later
    api: {
      baseURL: isGhPages ? `${normalizedBase}api/_content` : "/api/_content",
    },
    experimental: {
      clientDB: true,
    },
  },

  // TailwindCSS config path (generated by @nuxtjs/tailwindcss)
  css: ["@/assets/css/tailwind.css"],

  // Build settings
  build: {
    transpile: ["motion-v"],
  },

  // 链接 hover 时预取，配合 lazy 数据实现秒开
  experimental: {
    defaults: {
      nuxtLink: {
        prefetchOn: "interaction",
      },
    },
  },

  ssr: true,
  nitro: {
    preset: isGhPages ? "static" : process.env.NITRO_PRESET || "netlify",
    prerender: isGhPages
      ? {
          crawlLinks: false,
          failOnError: false,
          routes: prerenderRoutes,
        }
      : {
          crawlLinks: true,
          failOnError: false,
          routes: prerenderRoutes,
        },
    // 确保 API 路由不被预渲染，由 server 函数处理
    routeRules: {
      "/api/**": { ssr: false, headers: { "Cache-Control": "public, max-age=0, must-revalidate" } },
    },
  },

  // 强制使用单一 Vue 实例，避免多副本 Vue 导致运行时上下文异常
  vite: {
    resolve: {
      dedupe: ["vue", "vue-demi"],
    },
  },

  // Runtime config (placeholder for API keys etc.)
  runtimeConfig: {
    giscusToken: "",
    public: {
      giscusRepo: "",
      giscusRepoId: "",
      giscusCategory: "Announcements",
      giscusCategoryId: "",
      giscusTheme: "dark",
      statsBase: "",
      /** GitHub Pages 等静态部署无 /api，可指向 Netlify 等有后端的地址，如 "https://blog.xxx.netlify.app" */
      commentsApiBase: "",
      baseUrl: appBase,
    },
  },
});
